---
- name: Provision EC2 instance and deploy application
  hosts: app
  become: yes
  vars:
    app_repo: "https://oauth2:{{ lookup('env', 'ANSIBLE_GIT_TOKEN') }}@github.com/claymcenter/notification-service.git"
    app_dir: "/webapps/notification-service"
    docker_compose_file: "docker-compose.yml"
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - curl
          - gnupg
          - ca-certificates
          - lsb-release
        state: present
        update_cache: yes
    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started
    - name: Install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        state: present
        update_cache: yes
        
    - name: Add OpenResty GPG key
      ansible.builtin.get_url:
        url: https://openresty.org/package/pubkey.gpg
        dest: /usr/share/keyrings/openresty.gpg
        mode: '0644'
    - name: Add OpenResty APT repo
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/ubuntu {{ ansible_lsb.codename | lower }} main"
        filename: "openresty"
        state: present 
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes   
    - name: Install OpenResty
      apt:
        name: openresty
        state: present
        update_cache: yes
    - name: Clone the application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: HEAD
    - name: Run docker-compose up
      shell: |
        sudo docker-compose -f {{ app_dir }}/{{ docker_compose_file }} down || true
        sudo docker-compose -f {{ app_dir }}/{{ docker_compose_file }} up -d
      args:
        chdir: "{{ app_dir }}"
